.Dd 23/7/2021
.Dt debs2deb 1
.Os Linux
.Sh NAME
.Nm debs2deb
.Sh SYNOPSIS
.Nm
.Ar Ar path
.Op Ar packagename
.Sh DESCRIPTION
.Nm
find all debian packages upon given path and create installable offline respository from its
.\" .Sh BUGS              \" Document known, unremedied bugs
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner
